# generated by datamodel-codegen:
#   filename:  dispatch_task_response.json

from __future__ import annotations

from enum import Enum
from typing import List, Optional, Union

from pydantic import BaseModel, Field

from . import error, task_state


class Success(Enum):
    boolean_True = True


class Success1(Enum):
    boolean_False = False


class TaskDispatchResponse2(BaseModel):
    success: Optional[Success1] = None
    errors: Optional[List[error.Error]] = Field(
        None, description='Any error messages explaining why the request failed'
    )


class TaskDispatchResponse1(BaseModel):
    success: Success
    state: task_state.TaskState


class TaskDispatchResponse(BaseModel):
    __root__: Union[TaskDispatchResponse1, TaskDispatchResponse2] = Field(
        ...,
        description='Response to a task dispatch request',
        title='Task Dispatch Response',
    )
