# generated by datamodel-codegen:
#   filename:  fleet_log_response.json

from __future__ import annotations

from enum import Enum
from typing import List, Union

from pydantic import BaseModel, Field

from . import error, fleet_log


class Success(Enum):
    boolean_True = True


class Failure(Enum):
    boolean_False = False


class FleetLogResponse1(BaseModel):
    success: Success
    data: fleet_log.FleetLog


class FleetLogResponse2(BaseModel):
    success: Failure
    errors: List[error.Error] = Field(
        ..., description='Any error messages explaining why the request failed'
    )


class FleetLogResponse(BaseModel):
    __root__: Union[FleetLogResponse1, FleetLogResponse2] = Field(
        ..., description='Responding to a fleet log request', title='Fleet Log Response'
    )
