# generated by datamodel-codegen:
#   filename:  robot_commission_response.json

from __future__ import annotations

from enum import Enum
from typing import List, Optional, Union

from pydantic import BaseModel, Field

from . import error


class Success(Enum):
    boolean_True = True


class Result1(BaseModel):
    success: Success


class Success3(Enum):
    boolean_False = False


class Result2(BaseModel):
    success: Success3
    errors: Optional[List[error.Error]] = Field(
        None, description='Any error messages explaining why the request failed'
    )


class Result(BaseModel):
    __root__: Union[Result1, Result2]


class RobotCommissionResponse(BaseModel):
    commission: Result
    pending_dispatch_tasks_policy: Optional[Result] = None
    pending_direct_tasks_policy: Optional[Result] = None
