# generated by datamodel-codegen:
#   filename:  task_log_response.json

from __future__ import annotations

from enum import Enum
from typing import List, Union

from pydantic import BaseModel, Field

from . import error, task_log


class Success(Enum):
    boolean_True = True


class Failure(Enum):
    boolean_False = False


class TaskLogResponse1(BaseModel):
    success: Success
    data: task_log.TaskEventLog


class TaskLogResponse2(BaseModel):
    success: Failure
    errors: List[error.Error] = Field(
        ..., description='Any error messages explaining why the request failed'
    )


class TaskLogResponse(BaseModel):
    __root__: Union[TaskLogResponse1, TaskLogResponse2] = Field(
        ..., description='Responding to a task log request', title='Task Log Response'
    )
